# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-14 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('job_no', models.CharField(default='', max_length=16, null=True, verbose_name='工号')),
                ('dep_name', models.CharField(default='', max_length=16, null=True, verbose_name='部门名称')),
                ('position_name', models.CharField(default='', max_length=16, null=True, verbose_name='部门职位')),
                ('sex', models.CharField(default='', max_length=2, null=True, verbose_name='男')),
                ('power', models.CharField(default='', max_length=2, null=True, verbose_name='权限')),
                ('name', models.CharField(default='', max_length=30, null=True, verbose_name='姓名')),
                ('username', models.CharField(max_length=30, verbose_name='账号')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('img', models.CharField(default='', max_length=64, verbose_name='图片路径')),
                ('create_time', models.DateTimeField(default=None, null=True, verbose_name='入职时间')),
                ('email', models.EmailField(default=None, max_length=32, verbose_name='邮箱')),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Department')),
                ('position', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.Position')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
